### ISSUE TITLE
ELK Builds missing RitaAndAuroraMetronome.so

### ISSUE THREAD

**Issue by FinalEvilution** [ffont/source#1]
RitaAndAuroraMetronome.so is loaded by source_sushi_config.json but the installation instructions don't mention it 
and none of the ELK Build releases include it.

**Comment by ffont** [comment]
Hi,

Oups, that's a mistake. The metronome is something I added for testing purposes but is really unrelated to SOURCE itself.
Can you try this as a workaround before I release a fix:

1. Comment this line https://github.com/ffont/source/blob/b12595666aec740f3a064223a677927a4d71d8e7/fabfile.py#L87 so that Fabric script does not fail
2. Remove lines https://github.com/ffont/source/blob/b12595666aec740f3a064223a677927a4d71d8e7/elk_platform/source_sushi_config.json#L25-L44 (and the comma before) so that sushi does not try to load the metronome.

I think making these two changes should probably make the thing work. Alternatively, you can also compile the metronome project if you have the compiling toolchain set up. You can do it with the fabric script in the same way as you can compile SOURCE:

```
fab compile-metronome-elk
```

If none of the above work, you can also use the unmmodified sushi configuration and fabric file and simply place a copy of `SourceSampler.so` renamed to `RitaAndAuroraMetronome.so` at `source/elk_platform/metronome_plugin/Builds/ELKAudioOS/build/RitaAndAuroraMetronome.so` (in your local computer) so that another instance of SOURCE is deployed instead of the metronome, This should work. just fine.

**Comment by FinalEvilution** [comment]
Wow! thanks for the fast response.

fab send-elk-all failed do to an unrelated bug so i ended up reading the source code of fabfile.py and copying the files with scp which worked, I'm going to be busy for the next few days, I'll try to open an issue on the 7th.

After removing line 25 to 43 and the comma at line 24 in source_sushi_config.json sushi successfully started.

While i have your attention, in .gitmodules ff_meters uses git@github.com:ffont/ff_meters.git instead of https://github.com/ffont/ff_meters.git users who don't have GitHub SSH keys setup will get a "git@github.com: Permission denied (publickey)." error.

**Comment by ffont** [comment]
Hi, thanks for the heads up, I'll fix these things.

**Comment by neuhausler** [comment]
I followed your suggestions in regard to the missing plugin .. and instead of `fab compile-metronome-elk` I just run `fab send-elk-all` .. and that got everything running .. except, non of the sounds I download is playable .. all I hear is some noise .. will keep investigating

**Comment by ffont** [comment]
Hi, this might have to do with the Audio OS then. Can you run some simple tests in the board to play sounds? (outside SOURCE I mean).

**Comment by ffont** [comment]
In a new version to be merged soon I'm removing the metronome stuff from the code so closing this issue.
